# Generated by Django 2.0.dev20170211135840 on 2018-01-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeProductsWebsite', '0004_auto_20171205_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddField(
            model_name='review',
            name='num_reports',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(db_index=True, default='badr', max_length=50),
            preserve_default=False,
        ),
    ]
