# Generated by Django 2.0.dev20170211135840 on 2018-01-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeProductsWebsite', '0005_auto_20180109_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='num_reports',
            new_name='product_id',
        ),
    ]
