# Generated by Django 2.0.dev20170211135840 on 2018-01-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeProductsWebsite', '0006_auto_20180109_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='PrimeProductsWebsite.Product'),
        ),
    ]
