# Generated by Django 2.0.dev20170211135840 on 2018-01-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeProductsWebsite', '0007_auto_20180109_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(default='lait bebe', max_length=500),
            preserve_default=False,
        ),
    ]
